### ISSUE TITLE
Migrate landing page deployment

### ISSUE THREAD

**Issue by silvester-pari** [ESA-EarthCODE/portal#15]
Currently, the deployed landing page (reachable under https://earthcode.esa.int) is a placeholder (single HTML page). In the previous sprint, we set up the testing environment for the new multi-page and extendible landing page. This new setup should be made ready to be used in deployments (adapting GitHub CI, adapting Dockerfile etc.), and the newest contents of the landing page should be migrated to the new setup. A testing url should be added (e.g. testing.earthcode.esa.int). Finally, after successful setup of the testing deployment, the same setup should be used in production deployment and the domain https://earthcode.esa.int should point to the new deployment.

**Comment by silvester-pari** [comment]
Testing deployment has been set up at https://testing.earthcode.eox.at/

**Comment by GarinSmith** [comment]
Hi @silvester-pari , 
I have reviewed https://testing.earthcode.eox.at/  with @Chandra-TF and this looks fine to us,  so can you please go ahead and release to live?
Many thanks
Garin
